What is NLP?
NLP is a branch of AI that helps computers understand human language 
Allications of NLP
Chatbots, sentiment analysis, translation
Why does preprocessing matter?
Computers need clean, structured data inout as raw text can be messy and unstructured

### Load the IMDB dataset

In [9]:
import pandas as pd
url = "https://raw.githubusercontent.com/Ankit152/IMDB-sentiment-analysis/master/IMDB-Dataset.csv"
df = pd.read_csv(url)
df.head

<bound method NDFrame.head of                                                   review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]>

### Inspect the data

In [10]:
print(df.shape)
print(df.isnull().sum())
df.sample(3)

(50000, 2)
review       0
sentiment    0
dtype: int64

                                                  review sentiment
45589  I would have rated this film a minus 10 but sa...  negative
17434  I tuned in to this movie because there was not...  positive
30363  Wow this was a great Italian "ZOMBIE" movie by...  positive

### Install NLTK tools

In [12]:
!pip install nltk
import nltk
nltk.download('stopwords')
nltk.download('punkt')

Requirement already satisfied: nltk in c:\users\user\miniconda3\lib\site-packages (3.10.3)
Requirement already satisfied: defusedxml in c:\users\user\miniconda3\lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\user\miniconda3\lib\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in c:\users\user\miniconda3\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\miniconda3\lib\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in c:\users\user\miniconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\user\miniconda3\lib\site-packages (from tqdm->nltk) (0.4.6)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

### Clean the text

In [18]:
import re

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    tokens = text.split()
    tokens = [w for w in tokens if w not in stop_words]
    return tokens

df['cleaned_tokens'] = df['review'].astype(str).apply(clean_text)
df[['review', 'cleaned_tokens']].head(3)

,review,cleaned_tokens
0,One of the other reviewers has mentioned that ...,"[one, reviewers, mentioned, watching, oz, epis..."
1,A wonderful little production. <br /><br />The...,"[wonderful, little, production, br, br, filmin..."
2,I thought this was a wonderful way to spend ti...,"[thought, wonderful, way, spend, time, hot, su..."

### Original VS Cleaned

In [19]:
for i in range(3):
    print("ORIGINAL:", df['review'].iloc[i][:200], "...")
    print("CLEANED:", df['cleaned_tokens'].iloc[i][:20], "...")
    print("-" * 80)

ORIGINAL: One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me abo ...
CLEANED: ['one', 'reviewers', 'mentioned', 'watching', 'oz', 'episode', 'youll', 'hooked', 'right', 'exactly', 'happened', 'mebr', 'br', 'first', 'thing', 'struck', 'oz', 'brutality', 'unflinching', 'scenes'] ...
--------------------------------------------------------------------------------
ORIGINAL: A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece ...
CLEANED: ['wonderful', 'little', 'production', 'br', 'br', 'filming', 'technique', 'unassuming', 'oldtimebbc', 'fashion', 'gives', 'comforting', 'sometimes', 'discomforting', 'sense', 'realism', 'entire', 'piece', 'br', 'br'] ...
--------------------------------------------------------------------------------
ORIGINAL: I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is wi ...
CLEANED: ['thought', 'wonderful', 'way', 'spend', 'time', 'hot', 'summer', 'weekend', 'sitting', 'air', 'conditioned', 'theater', 'watching', 'lighthearted', 'comedy', 'plot', 'simplistic', 'dialogue', 'witty', 'characters'] ...
--------------------------------------------------------------------------------

### Save the cleaned dataset

In [20]:
df.to_csv('imdb_cleaned.csv', index=False)

### Insights

Preprocessing steps applied:
Lowercase — standardizes text so "Great" and "great" are treated the same
Remove punctuation & special characters — strips symbols that don't carry sentiment meaning
Remove numbers — removes digits that aren't relevant to sentiment
Tokenize — splits text into individual words
Remove stopwords — removes common words (the, is, and) that add noise without meaning